### ISSUE TITLE
Name collision with easyconfigs for Ray

### ISSUE THREAD

**Issue by lexming** [easybuilders/easybuild-easyconfigs#10757]
We have two easyconfigs with the same name for two unrelated applications:
* `Ray-0.8.4-foss-2019b-Python-3.7.4.eb` for https://github.com/ray-project/ray
* `Ray-2.3.1-iimpi-2019a.eb` for https://github.com/sebhtml/ray

These packages should have different names to be able to load them at the same time.

I propose to change the name of both packages to avoid wrong assumptions from the users:
* `Ray-0.8.4-foss-2019b-Python-3.7.4.eb` could be renamed to Ray-Framework or Ray-Project
*  `Ray-2.3.1-iimpi-2019a.eb` could be renamed to Ray-Assembler or Ray-DenovoAssembler

**Comment by verdurin** [comment]
@lexming just ran across this issue myself. I agree with your first choices for re-naming. Maybe contact @Darkless012 who created them?

**Comment by Darkless012** [comment]
Proposed a fix. But I opted for "Ray-project" since it is directly in github username, while "framework" is not mentioned anywhere in context with Ray. So users finding it will have some clue out of box.
The other had assembler in the title, so that was obvious choice.
There seems to be no other Easyconfigs dependent on any of the Ray projects. But since I've found one in archive, I've renamed that as well.
Sorry for the confusion, I should have checked the different programs.
