### ISSUE TITLE
Bazel-3.4.1 and Libstdc++ on CentOS7

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-easyconfigs#11058]
```
/tmp/eb-lbSnlc/bazel_mm5cxS2h/out/execroot/io_bazel/bazel-out/host/bin/external/com_google_protobuf/protoc: 
/usr/lib64/libstdc++.so.6: version GLIBCXX_3.4.21' not found (required by /tmp/eb-lbSnlc/bazel_mm5cxS2h/out/execroot/io_bazel/bazel-out/host/bin/external/com_google_protobuf/protoc)
```

If one takes the Bazel from the broken attempt from Easybuild, and do a simple `ml binutils; ml Java; ./compile.sh`, it works - so I don't know what is going on inside EB.

But if I add the following, it works:

```sh
prebuildopts  = 'BAZEL_LINKOPTS="-static-libstdc++ -static-libgcc" '
prebuildopts += 'BAZEL_LINKLIBS="-l%:libstdc++.a"'
```

No patches are necessary for this version anymore.

Solution comes from https://github.com/bazelbuild/bazel/issues/4510

**Comment by casparvl** [comment]
@surak which version of Bazel / which easyconfig does this apply to? 

> No patches are necessary for this version anymore.

I'm not sure what you mean here. I guess we either need to include your prebuildopts, or use some patch from the issue you reference?

@Flamefire I think you've played around a lot with Bazel, since you've done a fair amount of TensorFlow builds. Do you recognize this one?

**Comment by casparvl** [comment]
Small update: I've actually had a similar error before. At that point in time:
- We did not set `LD_LIBRARY_PATH` in our modules
- We used EasyBuild with RPATH support
Any chance you are doing the same?

Since you already have a solution, you probably don't need mine, but let me share it just in case:

For me, back then, setting the LD_LIBRARY_PATH was enough to get rid of the `GLIBCXX not found` error. The RPATHs would still not be set corectly, so I do that by loading a `patchelf` as `builddependency` and then add in the EasyConfig

```
postinstallcmds = ['patchelf --force-rpath --set-rpath $EBROOTGCCCORE/lib:$EBROOTGCCCORE/lib64 %(installdir)s/bin/bazel']
```

**Comment by Flamefire** [comment]
Yes I have the same and got it fixed. Patch is in my ec (forgot to upload) and in bazel upstream (search for my pr)
Will upload the bazel ec next week

**Comment by surak** [comment]
> @surak which version of Bazel / which easyconfig does this apply to?

Bazel 3.4.1, as I mentioned on the title.
> > No patches are necessary for this version anymore.
> I'm not sure what you mean here. I guess we either need to include your prebuildopts, or use some patch from the issue you reference?

Thing is, I checked Alex's PR for TF 2.3, and the ec for Bazel was missing. I did my own, and realized that all the previous patches (which are on our ec dir) are not necessary, as they have been applied.

The prebuildopts solve the issue, and so does his patch upstream, which is here: https://github.com/bazelbuild/bazel/pull/11860/files

**Comment by surak** [comment]
I tested now Bazel-3.4.1 without the prebuildopts, but with @Flamefire's patch. It does work.

**Comment by Flamefire** [comment]
--> https://github.com/easybuilders/easybuild-easyconfigs/pull/11086 for the Bazel EC with Patch
