### ISSUE TITLE
libxc regression test fails when using RPATH

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild-easyconfigs#11900]
this is because the regression test is done before the install step, so the library is not there yet

RPATH in `xc-regression` does include `$ORIGIN:$ORIGIN/../lib:$ORIGIN/../lib64` (I suppose CMAKE is adding these?), but the library in this particular case is at `$ORIGIN/../`

more generically, easybuild could either not use RPATH with test binaries, or run a sanity check on the any test binaries and make sure all required libraries can be found with the relative `$ORIGIN` paths?

**Comment by boegel** [comment]
The `$ORIGIN` entries are injected by EasyBuild itself, via the RPATH wrapper scripts. These also actively filter out any paths in the build directory, which is the cause of the problem here: the test binaries get built with `-L<builddir>` for example, and then our RPATH wrapper kicks out that path (to ensure it's not relied on for anything in the final installation). We ran into a very similar problem with FlexiBLAS (see #12476).

We could disable that filtering mechanism during the test step, but then we risk that build directory paths leak into the binaries/libraries that get installed. That's not a disaster though (just unclean), and hopefully the sanity check would catch it, so maybe that's a good way of fixing it?

@pescobar Did you ever run into problems like this, libraries not being found in the test step when building with RPATH enabled?

**Comment by pescobar** [comment]
@boegel I tried to reproduce the RPATH issues I had some time ago but this time it built ok. I cannot reproduce the issue. Not sure if this is related to changes in the latest easybuild release or changes in the application I am building
