### ISSUE TITLE
Python extension list

### ISSUE THREAD

**Issue by gjbex** [easybuilders/easybuild-easyconfigs#1303]
The list of extensions in the current Python 2.x Easyconfigs is pretty extensive, and some are rather exotic.  I think there is a case to be made for a bare version,

I would suggest to go with setuptools, pip, six, nose and to define modules for other packages, i.e., a scientific module to include numpy, scipy, matplotlib, mpi4py (perhaps pandas).

I understand these have been included for historic reasons, and that a change can and should not be made immediately, but it would be something to consider doing at some point.

**Comment by boegel** [comment]
@gjbex: the easyconfig without a `versionsuffix` have been 'batteries included' install, i.e. with a (potentially very long) list of extensions; basically, any extension that doesn't trigger an extra dependency is eligible to be added

the 'bare' versions (with `versionsuffix = '-bare'`) explicitly have *no* extensions at all, so that should stay like that

I guess a `-mininal` version makes sense too, e.g. with only `nose`, `pip`, `setuptools`, `six` as included extensions. This could be a good base for dedicated easyconfigs for `numpy`, `scipy`, etc.

Thoughts?

**Comment by Micket** [comment]
We do this nowdays.
