### ISSUE TITLE
Checksum for mvabund in R-4.0.4-foss-2020b.eb fails

### ISSUE THREAD

**Issue by signalbox2** [easybuilders/easybuild-easyconfigs#13117]
Build of R-4.0.4-foss-2020b.eb fails on the checksum of mvabund.

The file checksum of the file as downloaded from https://cran.r-project.org/src/contrib/Archive/mvabund/ is:
$ sha256sum mvabund_4.1.9.tar.gz
fa48c1cabe3a5bed35b0f31b02f55d9f15e57b3945cf3f407ddc9d3c9e29bb30  mvabund_4.1.9.tar.gz

the easyconfig has:

    ('mvabund', '4.1.9', {
        'checksums': ['60d09af4b82fe4945ef0b5aeb85aee2741ccc8a7b3cea26eecef4cf914787ea6'],

This will also impact the fosscuda easyconfig for R 4.0.4

**Comment by kelbstf** [comment]
Hello,

i have the same issue (EB 4.3.4, R-4.0.4).
i am an EasyBuild newbie, and i know this venue is a bugtracker.
But maybe someone of you can briefly help at the occasion of this specific case with a related fundamental question: 
how seasoned EasyBuild users are dealing with "checksum verification" issues in general. 
Simply hashing the checksum on one's own and "correcting" the EasyBuild file probably defeates the concept behind ;-) 
Is it always best to open an issue and ask the developers to have a look?
Or is there something one can do on one's own and contribute afterwards?

I would really appreciate any good advise.

Best

**Comment by boegel** [comment]
@signalbox2 @kelbstf The problem you're hitting was fixed in #13020 (EasyBuild v4.4.1), so you have a couple of options to deal with this:

* Use the latest version of EasyBuild (currently v4.4.1) => highly recommended!
* Copy the easyconfig file you're using, and tweak it to fix the checksum (`eb --copy-ec R-4.0.4-foss-2020b.eb .`, then edit `R-4.0.4-foss-2020b.eb` to change `60d09af4b82fe4945ef0b5aeb85aee2741ccc8a7b3cea26eecef4cf914787ea6` to `fa48c1cabe3a5bed35b0f31b02f55d9f15e57b3945cf3f407ddc9d3c9e29bb30`, and try using the fixed local easyconfig file);
* Use `--ignore-checksums` to instruct EasyBuild to not fail on a checksum mismatch (not recommended, only do this when you're confident that you won't download source tarballs from malicious places, or have already).
