### ISSUE TITLE
Boost & Python

### ISSUE THREAD

**Issue by wpoely86** [easybuilders/easybuild-easyconfigs#1421]
We now have a Boost with Python and without Python. This is annoying. Some deps use the version with Python, some without. We cannot use both. A proper solution needs to be found.

**Comment by wpoely86** [comment]
Possible solutions:
- Only use the Python version. The python version has everything the non python version has plus more.

- Handle this in the modules. Something like:
```
if( loaded(python) )
  load(Boost-Python)
else
  load(Boost)
```
If you want Boost-Python, you need to load Python prior to Boost. If one dep in the dep chain needs Boost-Python, it will be loaded. The problem here is who to promote an already loaded boost to boost-python

- Split Boost into multiple modules, like in Fedora: `boost-full` loads everything. `boost-python`, `boost-system`, .... An easyconfig can choose to only load what it needs. An added advantage is that all on the header only part of Boost can be degraded to a build dep.

One has the benefit of simplicity. Thee the benefit of elegance. 

Thought @boegel @fgeorgatos ?

**Comment by wpoely86** [comment]
After thinking so more, I think we shouldn't use versionsuffixes like we do. A versionsuffix shouldn't be used to indicate additional functionality. It's the same problem as with subtoolchains. We should be able to indicate that one easyconfig/module is the same as another + something extra.

**Comment by boegel** [comment]
option one has the downside of forcing a particular Python version, just because Boost happens to provide Python wrappers (which you may not care about);

option three has the downside of further supporting an explosion in the number of modules

you've outlined the problem with option two yourself

I agree that we're kind of abusing version suffixes, but I need not better option, for now...

**Comment by wpoely86** [comment]
The best solution (IMHO) for the moment is to use option 3 with 3 modules:
- `boost` (without python or mpi wrappers)
- `boost-python`
- `boost-mpi`

Those are the only components of Boost that I know of that require external libs.

**Comment by wpoely86** [comment]
Woeps, forgot the boost lapack binding. That would make four:
- `boost` (without python or mpi wrappers)
- `boost-python`
- `boost-mpi`
- `boost-lapack`

**Comment by fgeorgatos** [comment]
...and soon four will become more, for Boost being what it is (a pile of soft ... ;)

For the record, "biodeps" was born while trying to address this issue (ie. it is solution #1), described here:
https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/b/biodeps/biodeps-1.6-goolf-1.4.10-extended.eb
https://hpcbios.readthedocs.org/en/latest/HPCBIOS_2013-01.html

At some point, biodeps and co should be upgraded to latest and greatest (be my guest, if your feel like),
yet the major aim is/has been maximum compatibility (ie. only testing can tell what is truly good choice).

IMHO, I wouldn't dive into the combinatorial complexity of multiple variants (#3) nor conditional loads (#2) because dependent software builds can be potentially diverging and/or unmanageable. However, I am curious about what others may discover while going in those directions.

**Comment by wpoely86** [comment]
I wouldn't worry about adding more. Boost is still for a very large part a headers only library and the largest non-headers part is standalone. If fedora & debian can manage a split up boost, so can we (and they split it up per module).

That being said, I'm curious to what solution will be presented to the subtoolchain problems.

**Comment by wpoely86** [comment]
I think this is now irrelevant and can be closed.
