### ISSUE TITLE
Consider moving R to GCC level, splitting MPI extensions into a separate bundle

### ISSUE THREAD

**Issue by jfgrimm** [easybuilders/easybuild-easyconfigs#15195]
Unlike `Python`, `Perl`, etc., `R` sits at `foss` level due to requiring BLAS/LAPACK and MPI for various extensions. This pulls any easyconfigs depending on `R` all the way to `foss`, even if (and this often seems to be the case) they are not MPI-aware.
I would propose moving `R` itself to `GCC` (for flexiblas), and splitting any extensions that need to be at `foss` level into a separate bundle, similar to `Python`/`SciPy-bundle`

**Comment by branfosj** [comment]
MPI is definitely needed for `Rmpi`, but I am not sure much else beyond that and there are not a lot of R packages that depend on `Rmpi` (as far as I know).

**Comment by jfgrimm** [comment]
had a look at packages depending on MPI (directly or indirectly) in the current R 4.1.2 easyconfig:

| package  | dependency | library linked | 
| :-------------: | :-------------: | :------------- |
| `Rssa`  | `FFTW`  | `FFTW/3.3.10-gompi-2021b/lib/libfftw3.so.3`
| `hdf5r`  | `HDF5`   | `HDF5/1.12.1-gompi-2021b/lib/libhdf5_hl.so.200` 
| `Rmpi`  | `OpenMPI` | `OpenMPI/4.1.1-GCC-11.2.0/lib/libmpi.so.40`
| `sf`  | `netCDF`  | `netCDF/4.8.1-gompi-2021b/lib/libnetcdf.so.19`
| `terra`  | `netCDF`  | `netCDF/4.8.1-gompi-2021b/lib/libnetcdf.so.19`
| `fftw`  | `FFTW`  | `FFTW/3.3.10-gompi-2021b/lib/libfftw3.so.3`
| `fftwtools`  | `FFTW`  | `FFTW/3.3.10-gompi-2021b/lib/libfftw3.so.3`
| `imager`  | `FFTW`  | `FFTW/3.3.10-gompi-2021b/lib/libfftw3.so.3`
| `rgdal`  | `netCDF` | `netCDF/4.8.1-gompi-2021b/lib/libnetcdf.so.19`
| `ncdf4`  | `netCDF` | `netCDF/4.8.1-gompi-2021b/lib/libnetcdf.so.19`

**Comment by bartoldeman** [comment]
At Compute Canada we compile R with the gcccoreflexiblas toolchain:
https://github.com/ComputeCanada/easybuild-computecanada-config/blob/main/toolchains/gcccoreflexiblas.py
but this is a bit tricky as BLIS and OpenBLAS are at the GCC level (they have to be since Fortran interfaces differ between GCC and Intel), and having BLIS at both GCCcore and Intel can be confusing with an HMNS.

We also have
https://github.com/ComputeCanada/easybuild-computecanada-config/blob/main/toolchains/gccflexiblas.py

But it may be ok to simply use flexiblas as a dependency instead, and FFTW-serial.
Would need to look up if R can use HDF5/netCDF's MPI interfaces or not, if not it could use the -serial versions of those too.

**Comment by Micket** [comment]
R now sits at gfbf level, which is as low as it can get in our toolchains, becuase R itself depends on BLAS/LAPACK (it cant ever be moved to compiler level).
