### ISSUE TITLE
Test suite does not accept `SYSTEM` as valid toolchain for dep

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-easyconfigs#15901]
See https://github.com/easybuilders/easybuild-easyconfigs/runs/7471210039?check_suite_focus=true#step:8:160

**Comment by Micket** [comment]
I don't understand. Do you have an example easyconfig of what should work but doesnt?

**Comment by ocaisa** [comment]
I did, but to get the PR to pass the tests I changed it :P see https://github.com/easybuilders/easybuild-easyconfigs/pull/15900/commits/494fc0e98a6533788fb9de22fd12bd9118e2d4f9

**Comment by ocaisa** [comment]
A fix for this is now part of #15900

**Comment by Micket** [comment]
Discussed during the zoom meeting;
I hadn't realized that using the full toolchain dict just actually worked there, i thought it had to be `True`, so that completely negates everything I've said in this issue so far.

@boegel mentioned we might need to investigate the behaviour of dumpenv to see if we perhaps need to fix something in framework.

Otherwise, we were all very much in favour of doing this everywhere going forward.

**Comment by boegel** [comment]
Indeed, using `SYSTEM` rather than `True` is way more intuitive, so going forward with that definitely makes sense.

@ocaisa The workaround you had to do in the easyconfigs suite is probably a signal that we should change something in framework instead, i.e. avoid that `True` is being used when an easyconfig is being dumped, and use the `SYSTEM` constant instead?
Then there should be no need for the workaround you implemented in #15900...

**Comment by Micket** [comment]
>  i.e. avoid that `True` is being used when an easyconfig is being dumped, and use the `SYSTEM` constant instead?

whatever we pick, it'll have to resolve to something right? So any dump checker will have to account for the implied equality between `True` and `{'system': ....}` unless we really want to make one of those an error?

**Comment by Micket** [comment]
This is definitely solved (in fact, the test suite insists on this now)
