### ISSUE TITLE
`Gdk-Pixbuf-2.42.8-GCCcore-11.3.0.eb` RPATH sanity check failed: `libjpeg.so.8` not found

### ISSUE THREAD

**Issue by robogast** [easybuilders/easybuild-easyconfigs#16256]
### Context
I'm trying to build `Gdk-Pixbuf-2.42.8-GCCcore-11.3.0.eb` with `EasyBuild/4.6.1`, and get the following (truncated) error message:
```
== 2022-09-15 09:16:15,247 easyblock.py:4089 WARNING build failed (first 300 chars): Sanity check failed: One or more required libraries not found for /home/robertsc/.local/easybuild/Centos8/2021/software/Gdk-Pixbuf/2.42.8-GCCcore-11.3.0/bin/gdk-pixbuf-pixdata:   linux-vdso.so.1 (0x00007ffcf1571000)
        libgdk_pixbuf-2.0.so.0 => /home/robertsc/.local/easybuild/Centos8/2021/software/Gdk-
```
which after inspecting the logs turns out to be `libjpeg.so.8` not found:
```
One or more required libraries not found for /home/robertsc/.local/easybuild/Centos8/2021/software/Gdk-Pixbuf/2.42.8-GCCcore-11.3.0/lib/libgdk_pixbuf-2.0.so.0.4200.8:  linux-vdso.so.1 (0x00007ffdcb
1f1000)
        libm.so.6 => /lib64/libm.so.6 (0x000014ab4fbab000)
        libglib-2.0.so.0 => /home/robertsc/.local/easybuild/Centos8/2021/software/GLib/2.72.1-GCCcore-11.3.0/lib64/libglib-2.0.so.0 (0x000014ab4ffd7000)
        libgobject-2.0.so.0 => /home/robertsc/.local/easybuild/Centos8/2021/software/GLib/2.72.1-GCCcore-11.3.0/lib64/libgobject-2.0.so.0 (0x000014ab4ff78000)
        libgmodule-2.0.so.0 => /home/robertsc/.local/easybuild/Centos8/2021/software/GLib/2.72.1-GCCcore-11.3.0/lib64/libgmodule-2.0.so.0 (0x000014ab4ff6f000)
        libgio-2.0.so.0 => /home/robertsc/.local/easybuild/Centos8/2021/software/GLib/2.72.1-GCCcore-11.3.0/lib64/libgio-2.0.so.0 (0x000014ab4f9d0000)
        libpng16.so.16 => /home/robertsc/.local/easybuild/Centos8/2021/software/libpng/1.6.37-GCCcore-11.3.0/lib64/libpng16.so.16 (0x000014ab4f991000)
        libjpeg.so.8 => not found
        libpthread.so.0 => /lib64/libpthread.so.0 (0x000014ab4f771000)
        libc.so.6 => /lib64/libc.so.6 (0x000014ab4f3ac000)
        /lib64/ld-linux-x86-64.so.2 (0x000014ab4ff2d000)
        libpcre.so.1 => /home/robertsc/.local/easybuild/Centos8/2021/software/PCRE/8.45-GCCcore-11.3.0/lib64/libpcre.so.1 (0x000014ab4f366000)
        libffi.so.8 => /home/robertsc/.local/easybuild/Centos8/2021/software/libffi/3.4.2-GCCcore-11.3.0/lib64/libffi.so.8 (0x000014ab4ff5f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x000014ab4f162000)
        libz.so.1 => /home/robertsc/.local/easybuild/Centos8/2021/software/zlib/1.2.12-GCCcore-11.3.0/lib/../lib64/libz.so.1 (0x000014ab4f147000)
        libmount.so.1 => /home/robertsc/.local/easybuild/Centos8/2021/software/util-linux/2.38-GCCcore-11.3.0/lib64/libmount.so.1 (0x000014ab4f0e1000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x000014ab4eeca000)
        libblkid.so.1 => /home/robertsc/.local/easybuild/Centos8/2021/software/util-linux/2.38-GCCcore-11.3.0/lib/libblkid.so.1 (0x000014ab4ee69000)
        librt.so.1 => /lib64/librt.so.1 (0x000014ab4ec61000)

```

My best guess is that this is due to Meson being used as build system: https://github.com/mesonbuild/meson/issues/6541
If I `LD_PRELOAD=/home/robertsc/.local/easybuild/Centos8/2021/software/libjpeg-turbo/2.1.3-GCCcore-11.3.0/lib/libjpeg.so.8`, the build succeeds.

I'm not sure how to fix this issue without the `LD_PRELOAD` trick, but maybe @casparvl can help me with this issue when he comes back from holiday ;)

**Comment by angelinesalberto** [comment]
Hi @robogast I have the same problem, How did you fix i? 
the solution with LD_RELOAD, is doing 
export LD_RELOAD=PATH/libjpeg.so.8

??
Thanks in advance

**Comment by boegel** [comment]
I don't understand why this happens, since `libjpeg-turbo` is listed as dependency for `Gdk-Pixbuf`...

@robogast @angelinesalberto Can you confirm?

Can you share the output of `module show libjpeg-turbo/2.1.3-GCCcore-11.3.0`?

**Comment by casparvl** [comment]
@boegel it's failing the `RPATH` sanity check. So, during the build it's probably linked, but somehow doesn't make it into the RPATH. I seem to remember some issues with Ninja + RPATH support, see your own comment at https://github.com/easybuilders/easybuild-easyconfigs/issues/13880#issuecomment-912972340 and e.g. https://github.com/mesonbuild/meson/issues/6541 (though there are many related upstream issues...)

**Comment by boegel** [comment]
I'm running into the same problem now when trying to install `Gdk-Pixbuf/2.42.10-GCCcore-12.3.0` on our RHEL9 system, where we're opting into using RPATH as well (since that will become the default in EasyBuild 5.0).

Some observations:

* This problem did *not* occur when installing `Gdk-Pixbuf/2.42.10-GCCcore-12.3.0` in EESSI 2023.06, for some reason (even though RPATH is used there as well);
* The `libjpeg-turbo/.../lib64` directory is present in the RPATH section of the binaries in the build directory (for example `easybuild_obj/thumbnailer/gdk-pixbuf-thumbnailer`), which suggests the RPATH is fiddled with by `ninja` during the installation step... It's actually there *twice* (which may be another clue)
* The `libjpeg-turbo/.../lib64` directory is *not* present (anymore) in the RPATH section of the binaries in the *install* directory, which explains why `libjpeg-turbo.so.8` can not be found when `$LD_LIBRARY_PATH` is unset (that's done in the RPATH sanity check).

So the question is why Ninja thinks it's wise to strip out `/.../libjpeg-turbo/.../lib64` from the RPATH section, and how to prevent it from doing so.

**Comment by boegel** [comment]
This is basically due to a bug in Meson, as @bartoldeman pointed out in https://github.com/mesonbuild/meson/issues/6541#issuecomment-1175454508, which to date hasn't been fixed (maybe it's time for a PR to Meson @bartoldeman?).

For this particular case, it's possible to dance around this problem by making sure that the `libjpeg-turbo` libraries are installed to `lib`, rather than to `lib64`.
While EasyBuild will make sure that `lib` is symlinked to `lib64`, the reverse (symlinking `lib64` to `lib`) is not entirely equivalent, as this problem shows.

The problem is fixed for me after reinstalling `libjpeg-turbo` that is configured with `-DCMAKE_INSTALL_LIBDIR:PATH=lib`, see changes in #20386
