### ISSUE TITLE
R-4.2.1-foss-2022a.eb  execvp: printf: Argument list too long

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#16390]
R-4.2.1-foss-2022a.eb This version builds on /nodejs/16.15.1 will prompt execvp: printf: Argument list too long error, modifying ulimit -s 655360 will still cause an error

**Comment by hezhiqiang8909** [comment]
![image](https://user-images.githubusercontent.com/49931482/195290991-fcc23f01-cac1-46f8-a35b-b2338bad124d.png)
![image](https://user-images.githubusercontent.com/49931482/195291265-8a042eca-b5cd-4e88-ba51-234097719ff5.png)

**Comment by hezhiqiang8909** [comment]
This issue was resolved by adding the --buildpath= option to specify the build path

**Comment by boegel** [comment]
The issue here most likely was that the default build path was relatively long, which leads to some compiler command involving a lot of files being too long for bash to handle, we've seen this in other places too (see for example https://github.com/easybuilders/easybuild-easyblocks/commit/0568a480e77b2c878ec28e362d69fe8a721afc36)
