### ISSUE TITLE
hwloc-1.6.2 issue during BWA-0.7.4-goolf-1.4.10.eb

### ISSUE THREAD

**Issue by necrolyte2** [easybuilders/easybuild-easyconfigs#1668]
I'm testing out the project and pretty much starting from scratch. I wanted to install the 
`BWA-0.7.4-goolf-1.4.10.eb` easyconfig.

First error I hit was that that eb file was missing
`tar_config_opts=True` which was related to hpcugent/easybuild-easyblocks#30
I fixed that(and eventually can make a pull request if somebody doesn't fix it before I do), but then ran into an issue with the building stage which I'm pretty sure is related to #1605 

Log file: https://gist.github.com/necrolyte2/8b03c2cc472b5e60a782

The strange thing is I can build the code that easybuild has downloaded fine if I do it manually

```
module use /home/AMED/tyghe.vallard/.local/easybuild/modules/all
module load GCC/4.7.2
cd ~/.local/easybuild
tar xzvf sources/h/hwloc/hwloc-1.6.2.tar.gz
am__tar='tar chf - "$$tardir"'  am_cv_prog_tar_ustar='easybuild_avoid_ustar_testing'  am__untar='tar xf -'  ./configure --prefix=/home/AMED/tyghe.vallard/.local/easybuild/software/hwloc/1.6.2-GCC-4.7.2
make -j 8
```

**Comment by boegel** [comment]
It seems like this was left unanswered, my apologies...

The reason why it works for you when doing the build manually is because you're not setting `$CFLAGS` like EasyBuild does, and hence you're not telling the compiler to generate AVX2 instructions if it can.

Only with AVX2 instructions will you run into problems when linking with an old binutils.

Our solution to this issue is to include binutils in recent toolchains, underneath GCC, cfr. #1695.

Let us know if this helps.

**Comment by Micket** [comment]
Our CI requires builddep on binutils for this reason for many years now.
