### ISSUE TITLE
get rid of googlecode.com source_urls

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#1698]
`GOOGLECODE_SOURCE`:
- [ ] gperftools 2.1 => http://sourceforge.net/projects/gperftools.mirror/files/
- [ ] likwid 3.0.0 => no alternatives??
- [ ] mpi4py 1.3 =? PyPI
- [ ] numexpr 2.0.1, 2.2.2 => PyPI
- [ ] OpenPGM 5.2.122 => no alternatives??
- [ ] protobuf 2.4.0a, 2.5.0 => 2.5.0 @ https://github.com/google/protobuf/releases, no alternatives for 2.4.0a??

`googlecode.com`:
- [x] argparse 1.2.1 and 1.3.0 (in Python easyconfigs) => PyPI (see #1697)
- [ ] BEDTools 2.17.0
- [ ] BitSeq 0.7.0
- [ ] beagle-lib 20120124, 20141202
- [ ] CD-HIT 4.6.1
- [ ] CFR++ 0.57
- [x] deap 0.9.1 (in Python easyconfigs) (see #1699)
- [ ] Go 1.2.1
- [ ] git 1.7.12, 1.8.2, 1.8.3 => https://www.kernel.org/pub/software/scm/git/
- [ ] gtest 1.6.0
- [ ] h5py 2.0.1, 2.1.3
- [ ] IDBA-UD 1.1.1
- [ ] netcdf4-python 1.0.7 => https://github.com/Unidata/netcdf4-python/archive/v1.0.7rel.tar.gz
- [ ] OpenPGM 5.2.122
- [ ] PRANK 130820, 140110
- [ ] PhyML 20120412, 20131016
- [ ] packmol 13.243
- [ ] petsc4py 3.3
- [ ] SCOOP 0.5.3, 0.6.2
- [ ] STAR 2.3.0e
- [ ] sparsehash 2.0.2
- [ ] sympy 0.7.2

**Comment by rjeschmi** [comment]
netcdf4-python:
https://github.com/Unidata/netcdf4-python
git:
https://www.kernel.org/pub/software/scm/git/

**Comment by jayvdb** [comment]
Hi @boegel , I think you could use https://github.com/jayvdb/pypidb to work these out.  Here are the ones that resolve - not sure if they are correct.

* sparsehash: https://github.com/syllog1sm/cython-sparsehash
* SCOOP: https://github.com/soravux/scoop
* h5py: https://github.com/h5py/h5py
* netcdf4: https://github.com/Unidata/netcdf4-python
* argparse: https://github.com/ThomasWaldmann/argparse
* petsc4py: https://bitbucket.org/petsc/petsc4py
* numexpr: https://github.com/pydata/numexpr
* STAR: https://github.com/dbrgn/star
* deap: https://github.com/DEAP/deap
* sympy: https://github.com/sympy/sympy
* protobuf: https://github.com/protocolbuffers/protobuf
* mpi4py: https://bitbucket.org/mpi4py/mpi4py

And then PyPI Go points to https://code.google.com/p/go-tool

It might be worth automating it, because then you can also update other URLs when the repos move around.  e.g. BitBucket repos are on the move rapidly atm.

**Comment by Micket** [comment]
Scanning through the easyconfigs we haven't deprecated and there are no googlecode sources left.
