### ISSUE TITLE
It is recommended to update Rosetta. The current version is too low

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#17616]
--try-software-version This parameter is not very useful. When encountering relevant configuration files and performing patch operations, it is difficult to solve the patching steps of new versions and lower versions between different versions.

**Comment by Micket** [comment]
PRs are welcome. Please feel to do all the work of figuring out any patches, updates, configuration options, then open a finished PR that we can test for inclusion. It's not useful to keep this issues requesting updates, since, of course, it's always "recommended to update" just about every conceivable software.
