### ISSUE TITLE
QUAST-5.0.2 Add --no-check-certificate parameter

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#17651]
When building the QUAST-5.0.2 software package, it prompts that the build failed. The reason is that the return code of executing a command is not 0. Specifically, when executing a sanity check, this sanity check is used to check whether the build is successful Yes, after I added the --no-check-certificate parameter to the location of the eb file, the installation was successful
![image](https://user-images.githubusercontent.com/49931482/229575712-1cc17c9e-a377-40ff-9513-7b29172dfbab.png)
![image](https://user-images.githubusercontent.com/49931482/229575781-bcd7d011-7111-4d9f-a113-5e88ab6708d9.png)

**Comment by Micket** [comment]
The purpose of SSL checks is to verify that the download can be trusted, it's not advised to disable this. Either their webserver has temporary issues with their certificate expiring, or they were hacked, or your local CA's on your host are out of date and should be updated. 

Newer versions seems to have done away with this separate test directory alltogether, so i think this issue is resolved no matter what.
