### ISSUE TITLE
Add TBPlaS eb installation template

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#17673]
Hello, easybuild technical support team, can this software add an installation template http://www.tbplas.net/install.html#get-the-source-code

**Comment by Micket** [comment]
PRs are welcome. Please feel to do all the work of figuring out any patches, updates, configuration options, then open a finished PR that we can test for inclusion. It's not useful to keep this issues requesting updates, since, of course, it's always "recommended to update" just about every conceivable software.
