### ISSUE TITLE
Segmentation fault when trying to test ResistanceGA

### ISSUE THREAD

**Issue by ItIsI-Orient** [easybuilders/easybuild-easyconfigs#17692]
I have built ResistanceGA using [this easyconfig](https://github.com/vscentrum/vsc-software-stack/blob/main/29_ResistanceGA/ResistanceGA.eb) and everything seems to work just fine, but when I tried to do a test of the installation as mentioned in the [ResistanceGA manual](https://petermanresearch.weebly.com/uploads/2/5/9/2/25926970/julia_guide.pdf), I get Segmentation fault when trying to run `JuliaCall::julia_setup(JULIA_HOME)`. What seems weird is that I have managed to create a workaround by adding `$EBROOTJULIA/lib/julia` to `LD_LIBRARY_PATH`, but that isn't the best approach in dealing with this error.

Any ideas about how I should approach this?

**Comment by boegel** [comment]
What's puzzling me about this is that `$EBROOTJULIA/bin/julia` has an RPATH set that includes `$ORIGIN/../lib/julia`, so adding `$EBROOTJULIA/lib/julia` to `$LD_LIBRARY_PATH` shouldn't matter at all...

Any ideas on this @lexming, @bartoldeman ?

**Comment by boegel** [comment]
@bartoldeman Any ideas here?

**Comment by lexming** [comment]
This issue is caused by the paths prepended to `LD_LIBRARY_PATH` by other modules. Julia uses `RUNPATH` (not `RPATH`) to find its own libraries. This means that `LD_LIBRARY_PATH` still has precedence and loading any module that pulls a full toolchain (like `R` in `ResistanceGA`) will _replace_ many libraries in Julia with those from the loaded modules.

#20103  solves this issue by using a wrapper to execute `julia`
