### ISSUE TITLE
rgl R package included as extension requires OpenGL/Mesa as dependency

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#1935]
from a failed test report on a system where Mesa was not installed system-wide (see https://github.com/hpcugent/easybuild-easyconfigs/pull/1744#issuecomment-135735922):

```
== 2015-08-28 12:44:48,505 main.run DEBUG cmd "R CMD INSTALL /data/gent/gvo000/gvo00002/vsc40023/EasyBuild/sources/r/R/extensions/rgl_0.95.1247.tar.gz   --library=/data/gent/gvo000/gvo00002/vsc40023/KUL_easybuild/software/R/3.2.1-foss-2015b/lib64/R/library --no-clean-on-error" exited with exitcode 1 and output:
* installing *source* package ‘rgl’ ...
...
checking for X... libraries , headers 
checking GL/gl.h usability... no
checking GL/gl.h presence... no
checking for GL/gl.h... no
checking GL/glu.h usability... no
checking GL/glu.h presence... no
checking for GL/glu.h... no
configure: error: missing required header GL/gl.h
ERROR: configuration failed for package ‘rgl’
```

**Comment by nathanhaigh** [comment]
I've just come across this on my Ubuntu systems.

One solution is to add `libGLU` as a dependency. However for my toolchain (foss-2015b), this would mean a load of new easyconfigs. If this is the way to go I can start a PR?

**Comment by boegel** [comment]
I don't think including Mesa as a dependency in the R easyconfigs just because of a single extension is a good idea...

So, we should flesh out `rgl` (and any extensions that depend on it) in a separate bundle, which includes `Mesa` as a dependency?

**Comment by verdurin** [comment]
Just come across this one on a CentOS 7 system, with `2.7.0`.

**Comment by verdurin** [comment]
Another confirmation that this occurs on an Ubuntu 14.04 VM, with 2.7.0, as @nathanhaigh mentioned above.

**Comment by verdurin** [comment]
@boegel - your separate bundle idea sounds the least painful to me.

**Comment by dominikborkowski** [comment]
Just adding another 'me too', CentOS 7.3 with R-3.3.1-foss-2016b.eb. Not sure what the right solution would be, for the time being we'll add a dependency for libGLU-9.0.0-intel-2016b.eb

**Comment by shawarden** [comment]
For me rgl requires both X11 and libGLU and additionally Cairo unsurprisingly requires cairo

I either add...

    ('X11', '20160819'), # for rgl
    ('libGLU', '9.0.0'), # for rgl
    ('cairo', '1.14.6'), # for Cairo

...to the eb file or manually load X11, libGLU and cairo modules on the build node if there's no compatible versions for the given tool-chain.

**Comment by boegel** [comment]
We now include `Mesa`, `libGLU` & `cairo` as dependencies in the recent R easyconfigs, so I'm closing this.

**Comment by zwintrob** [comment]
Another me too, I just ran into this on Fedora 27 and the installing mesa-libGLU-devel from terminal solved it for me. I know this is an old thread but, still relevant.

**Comment by sebacea** [comment]
The problem is still there in my configuration:

sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
 [1] LC_CTYPE=es_CL.UTF-8       LC_NUMERIC=C               LC_TIME=es_CL.UTF-8       
 [4] LC_COLLATE=es_CL.UTF-8     LC_MONETARY=es_CL.UTF-8    LC_MESSAGES=es_CL.UTF-8   
 [7] LC_PAPER=es_CL.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=es_CL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ProfessR_2.3-5 arsenal_3.2.0 

loaded via a namespace (and not attached):
 [1] compiler_3.6.0  magrittr_1.5    R6_2.4.0        Matrix_1.2-17   tools_3.6.0     htmltools_0.3.6
 [7] Rcpp_1.0.1      grid_3.6.0      knitr_1.22      xfun_0.7        digest_0.6.18   testthat_2.2.0 
[13] rlang_0.3.4     RPMG_2.2-2      lattice_0.20-38

I solved it following: https://r-forge.r-project.org/tracker/?group_id=234&atid=946&func=detail&aid=6553

**Comment by mintzj** [comment]
Hi all, I had a similar problem, which was resolved by installing _libglu1-mesa-dev_ and _mesa-common-dev_.  The error I originally received was:

> checking for libpng-config... yes
> configure: using libpng-config
> configure: using libpng dynamic linkage
> checking for X... libraries , headers 
> checking GL/gl.h usability... no
> checking GL/gl.h presence... no
> checking for GL/gl.h... no
> checking GL/glu.h usability... no
> checking GL/glu.h presence... no
> checking for GL/glu.h... no
> configure: error: missing required header GL/gl.h

In the process of trying to figure this out, I installed _mesa-common-dev_, which got through to an error on glu.h. 

> checking GL/gl.h usability... yes
> checking GL/gl.h presence... yes
> checking for GL/gl.h... yes
> checking GL/glu.h usability... no
> checking GL/glu.h presence... no
> checking for GL/glu.h... no
> configure: error: missing required header GL/glu.h

Installing _libglu1-mesa-dev_ resolved the problem.
