### ISSUE TITLE
Lua file for Anaconda3/2023.09-0 is missing the execute line

### ISSUE THREAD

**Issue by rlpitts** [easybuilders/easybuild-easyconfigs#19955]
I just installed Anaconda3/2023.09-0 for a user, but she was unable to activate her environments in the new version. With a little digging, I discovered the .lua file is missing the following line, which upon manual insertion solved the user's problem:
`execute{cmd=". .../software/Anaconda3/2023.09-0/etc/profile.d/conda.sh", modeA={"load"}}` (ellipses inserted to protect our servers).

I'm not sure how to submit this fix as a pull request because I'm pretty new to EasyBuild and lua,

**Comment by Xaraxia** [comment]
I suspect an issue at your end re 2023.07, because that doesn't occur at our site. Anaconda adds itself into a user's .bashrc by default and it can break a lot of things. Anaconda is annoying like that.

As for the other, I'm guessing that command was added by somebody else at some point. It will not work for users using csh.

Somebody has worked out how to do this with LUA here: https://github.com/CHPC-UofU/Lmod-setup/blob/master/2019.03.lua so you could try adding that to your module file and see if it works.

**Comment by Micket** [comment]
yeah this populates permanent things into the user home dir when loading stuff. You are of course welcome to customize your modules like this, but it's more the job of a site-specific hook as I really don't think we want to enable these for all. 

If the anaconda environment would be added as part of loading and unloading modules themselves, cleanly (no fiddling with .bashrc) i would probably welcome it (though still only a "maybe", depends on what it does).

As such, i think there is currently nothing about this we really wish to change in EB.
