### ISSUE TITLE
remove Cython extension from future Python-bundle-PyPI easyconfigs

### ISSUE THREAD

**Issue by smoors** [easybuilders/easybuild-easyconfigs#20524]
rationale:
- `Cython` should be a builddep not a dep in most cases
- some Python packages require a specific Cython version
- the installation `Python-bundle-PyPI` itself currently does not need Cython

it's probably too risky to do this for the existing `Python-bundle-PyPI` easyconfigs, but i want to make sure the next version does not have `Cython` in it (or only as a builddep if needed).

**Comment by WilleBell** [comment]
This would be useful for #20525 where `Cython` had to be included as a dependency after  `Python-bundle-PyPI` because `sci-kit-learn` v1.4.2 requires a newer `Cython` version to build. Same workaround was used for [Cartopy-0.22.0-foss-2023a.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/c/Cartopy/Cartopy-0.22.0-foss-2023a.eb) . They workaround works, but having 2 versions in the path even though only 1 is used doesn't seem ideal. Neither is having a dependency that is only needed as build dependency.

**Comment by boegel** [comment]
I guess we can drop it from the latest `Python-bundle-PyPI` (like done in #21233), since that's not included in an EasyBuild release yet (cfr. #20827), but doing this for older `Python-bundle-PyPI` versions is likely too painful at this point.

It's also not a huge problem I think, since you can always shadow the `Cython` included in `Python-bundle-PyPI` by specifying an extra build dependency (or am I missing something here)?

**Comment by smoors** [comment]
> It's also not a huge problem I think, since you can always shadow the `Cython` included in `Python-bundle-PyPI` by specifying an extra build dependency (or am I missing something here)?

for some reason adding cython as an extra build dep doesn't work, you have to add it as a real dep. that workaround works, but not ideal as @WilleBell explained above

**Comment by smoors** [comment]
closing this as https://github.com/easybuilders/easybuild-easyconfigs/pull/21233 is merged

**Comment by boegel** [comment]
> > It's also not a huge problem I think, since you can always shadow the `Cython` included in `Python-bundle-PyPI` by specifying an extra build dependency (or am I missing something here)?
> 
> for some reason adding cython as an extra build dep doesn't work, you have to add it as a real dep. that workaround works, but not ideal as @WilleBell explained above

Ah, I guess that's because the build dependencies are loaded first...
