### ISSUE TITLE
Update amber24 and ambertoosl 24

### ISSUE THREAD

**Issue by hezhiqiang8909** [easybuilders/easybuild-easyconfigs#21402]
I hope there will be a branch or update of amber24 and ambertoosl 24 eb executable files, thanks

**Comment by hezhiqiang8909** [comment]
How to install amber24 and ambertoosl 24 using amber22 and ambertoosl 22 version templates or is there a branch that can provide installation? It seems that the --try-software-version parameter cannot match

**Comment by Micket** [comment]
PRs are welcome. Please feel to do all the work of figuring out any patches, updates, configuration options, then open a finished PR that we can test for inclusion. It's not useful to keep this issues requesting updates, since, of course, it's always "recommended to update" just about every conceivable software.
