### ISSUE TITLE
Missing zlib dep in several easyconfigs?

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#3204]
Today I was testing builds of `BWA` and `Bowtie2` and in both cases the builds failed because there were no `zlib` headers.

`zlib` isn't listed as a dependency for either of those, and I'm wondering whether there are more easyconfigs with a similar problem?

**Comment by boegel** [comment]
@verdurin probably, we don't have a good setup yet to test builds in isolation of the OS; I'm looking into Nix/Guix for that, but only in between other things...

**Comment by verdurin** [comment]
@boegel - okay, I'll submit a PR to cover the cases I know about, and leave this open as a tracker bug.

**Comment by JackPerdue** [comment]
It gets a little tricky since shutting down OpenSSL in EB (quite rightfully)....  openssl-devel on RHEL systems have zlib-devel as a dependency which sometimes cause EB to link the system zlib instead of the zlib module you've loaded (sometimes, usually badly written installers).  I try to run a very clean no-devel build system just to make sure it all goes into modules, but that one, given its use by openssl, gets under the radar at times (depending upon what I'm building).

**Comment by Micket** [comment]
We are pretty good including zlib dependency wherever we should these days.
