### ISSUE TITLE
mpfr patch in GCCcore GCC

### ISSUE THREAD

**Issue by shahzebsiddiqui** [easybuilders/easybuild-easyconfigs#3938]
Hello,

There seems to be a  confusion why there are mpfr patch in both GCC and GCCcore. Can you please put them in one place so it is clear which patch we need to get. 

https://github.com/hpcugent/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/g/GCC
https://github.com/hpcugent/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/g/GCCcore

Also if you have a patch for mpfr inside GCC tree, wouldn't it make sense when building MPFR via Easybuild to have these patches. Right now they are not present.

Currently, the only patch we have is https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/m/MPFR/MPFR_ictce_remove-deprecated-mp.patch

**Comment by boegel** [comment]
Currently, patches are required to be in the same directory as the easyconfig files that use them, which is why we have copies in both the `GCC` and `GCCcore` directory (the latter is a regular GCC installation, which is made part of the `GCC` bundle that also includes `binutils`).

I guess we could do better here by just symlinking the duplicate patches rather than copying them.

Good point about the `MPFR` builds themselves not including the patches, they should.

@wpoely86 Thoughts?

**Comment by wpoely86** [comment]
Maybe we should just download them? It are upstream patches after all.
