### ISSUE TITLE
unnecessary build dependency in testpath-0.3-intel-2016a-Python-2.7.11.eb

### ISSUE THREAD

**Issue by andreas-h** [easybuilders/easybuild-easyconfigs#3956]
I'm wondering why in `testpath-0.3-intel-2016a-Python-2.7.11.eb`, there is pip-8.0.2 as build dependency, as the Python-2.7.11 already has pip in the `exts_list`?

**Comment by boegel** [comment]
There's indeed no reason, this slipped in because with Python 2.7.10 we had to include a newer pip as build dependency because the one included was too old (should be pip 8.x or newer which has support for `pip install --prefix`).

Are you up for opening a PR to clean that up in the `testpath` easyconfigs (and maybe also in others)?

**Comment by andreas-h** [comment]
Yes, can do that, but it'll be some time before I can work on this.

**Comment by boegel** [comment]
@andreas-h ping?

**Comment by Micket** [comment]
Maybe this was fixed, or things just got archived away. Doesn't matter.
