### ISSUE TITLE
How to pass build options to Boost

### ISSUE THREAD

**Issue by SethosII** [easybuilders/easybuild-easyconfigs#4819]
I'm trying to build version `1.54.0` of `Boost` with the `foss-2016b` toolchain. I managed to get it to work manually with some patches but I fail to write a working EasyConfig.

The part I'm stuck at is how to pass options to the `./b2` command. When building it manually I used this:

```
./b2 install --prefix=/beegfs/tools/16.04/Boost/1.54.0-0/ variant=release threading=multi cxxflags="-std=c++0x"
```

The options I have tried are `configopts`, `buildopts`, `prebuildopts`, and `installopts` like so:

```
buildopts = 'variant=release threading=multi cxxflags=-std=c++0x'
```

But these are not passed down to the compiler and therefore te build step fails (`-std=c++0x` is the needed option). How can I accomplish this?

**Comment by boegel** [comment]
@SethosII `buildopts` is supposed to be work, but it's totally ignored by the Boost easyblock right now...

This is fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/1207.

Can you please try this updated easyblock, and see if it fixes your problem?
* download `boost.py` via https://github.com/easybuilders/easybuild-easyblocks/pull/1207/files -> `View` -> `Raw`
* make EasyBuild use it via `eb --include-easyblocks boost.py ...`

**Comment by SethosII** [comment]
@boegel Thanks, the `buildopts` are passed through correctly with this EasyBlock!
