### ISSUE TITLE
Missing pkg-config in builddependencies

### ISSUE THREAD

**Issue by renatopancheri** [easybuilders/easybuild-easyconfigs#5571]
those easyconfigs need pkg-config as a builddependencies 
- **fontconfig**
- **gnuplot**
- **harfbuzz**
- **Pango**

Build will fail if you dont have system pkg-config installed
I installed specifically:

`fontconfig/2.12.4-GCCcore-6.4.0`
`gnuplot/5.2.2-foss-2017b`
`HarfBuzz/1.7.1-foss-2017b`
`Pango/1.40.14-foss-2017b`

**Comment by boegel** [comment]
@renatopancheri Thanks for the bug report! Are you up for submitting pull requests to add `pkg-config` as build dependency for these?

**Comment by renatopancheri** [comment]
@boegel I can make the pull request, i would like to know if:

- i have to modify all the eb including the old ones

- i should use `pkg-config/0.29.2` for all eb or use older version for older eb

**Comment by boegel** [comment]
@renatopancheri It's probably not worth the effort to do this for *all* easyconfigs for these software packages, I'd stick to the most recent ones, i.e.:

* fontconfig 2.12.x
* gnuplot 5.x
* HarfBuzz 1.3.x (maybe also 1.2.x)
* Pango 1.40.x

I would try using pkg-config 0.29.2, unless you run into problems due to version conflicts etc. (which I wouldn't expect to occur, since `pkg-config` is only a build dependency).

**Comment by boegel** [comment]
fixed in #5580, let's follow up there
