### ISSUE TITLE
OpenMPI/2.1.1-GCC-6.4.0-2.28 build fails if ucx-devel is installed on system

### ISSUE THREAD

**Issue by jabl** [easybuilders/easybuild-easyconfigs#5805]
The easyconfig OpenMPI/2.1.1-GCC-6.4.0-2.28 (part of the foss/2017b toolchain) fails to build with the error below:

<pre><code>
Making all in mca/pml/ucx
make[2]: Entering directory `/l/easybuild/build/OpenMPI/2.1.1/GCC-6.4.0-2.28/openmpi-2.1.1/ompi/mca/pml/ucx'
  CC       pml_ucx.lo
  CC       pml_ucx_request.lo
  CC       pml_ucx_datatype.lo
  CC       pml_ucx_component.lo
  CCLD     libmca_pml_ucx.la
libtool:   error: require no space between '-L' and '-lrt'
make[2]: *** [libmca_pml_ucx.la] Error 1
</code></pre>

Removing the rpm package "ucx-devel" fixes it. ucx-devel is installed as part of Mellanox OFED drivers (this is on CentOS 7). Most likely the culprit is https://github.com/open-mpi/ompi/issues/4345

**Comment by boegel** [comment]
@jabl Thanks for reporting this...

Since this is a bug upstream, how do you suggest we handle this, try to patch the `configure` script?

**Comment by boegel** [comment]
@wpoely86 This is the same issue you were seeing in #5768?

**Comment by wpoely86** [comment]
Yes, it's the same.

**Comment by boegel** [comment]
@jabl It's not as simple as just applying the patch from https://github.com/ggouaillardet/ompi/commit/7a3ace19e8e35a2e6a5fa756dee1259a1c7de67f, we'll need to regenerate the `configure` script too...

@wpoely86 Do you think it's worth the trouble to try and patch this? I'm inclined to try and fix this since this affects `OpenMPI-2.1.2-GCC-6.4.0-2.28.eb` which is part of `foss/2018a`...

Can we come up with a direct patch for the `configure` script?

**Comment by boegel** [comment]
Or maybe we should include `--without-ucx` in the easyconfig for this particular Open MPI version to dance around this, as suggested by @hajgato on the EasyBuild mailing list?

**Comment by boegel** [comment]
@jabl @wpoely86 Proposed @OleHolmNielsen Proposed workaround in #5949

**Comment by boegel** [comment]
follow-up in #5949
