### ISSUE TITLE
EasyBuild/3.5.3,  zlib-1.2.8-GCC-5.1.0-binutils-2.25.eb,  gcc fails on not finding ISL

### ISSUE THREAD

**Issue by pmatousu** [easybuilders/easybuild-easyconfigs#6164]
GCC build fails on not finding ISL.
Should not ISL be among dependencies?

**Comment by boegel** [comment]
@pmatousu Please share the exact error you're seeing?

**Comment by boegel** [comment]
@pmatousu Can you check the contents of `config.log` in the build directory? Using `eb --debug` or `eb --trace` can help in tracking it down.

**Comment by pmatousu** [comment]
I am not sure, we should chase this case more - I think it could be related to my system. What do you think? I have meantime successfully (with some issues related to lib and lib64) build GCCcore/4.9.3 and maybe I could try to replicate this GCC-5.1.0 build using EB built GCC493. To start from some known state? Do you agree?

**Comment by boegel** [comment]
It would be good to know what is causing this problem, since we're not seeing it.

GCC 4.9.3 is quite old, you should probably aim for using a significantly more recent compiler, like `GCCcore/6.4.0` which is the basis for the `2017b` and `2018a` common toolchains (see http://easybuild.readthedocs.io/en/latest/Common-toolchains.html), for which a lot of easyconfigs are available...

**Comment by pmatousu** [comment]
I will try to reproduce it with higher versions of tool chain.

**Comment by Micket** [comment]
This is long since outdated and likely hasn't been an issue for years now.
