### ISSUE TITLE
Python-3.6.4-intel-2018a hashlib broken

### ISSUE THREAD

**Issue by mstud** [easybuilders/easybuild-easyconfigs#6510]
Hi, I've been trying to build Boost with Python 3.6.4 but it fails with the following error:
AttributeError: module '_hashlib' has no attribute 'openssl_shake_256'
The problem seems to be that the Python-3.6.4-intel-2018a installation had some problems, even though it ran through without aborting, which I believe is problematic. I have found the following mailing list posting:
https://www.mail-archive.com/easybuild@lists.ugent.be/msg04295.html
Apparently it is a bug in the specific version of the intel compiler that leads to this.
However, why hasn't this been addressed so far?
And why does EasyBuild still report the build of Python as successful even though such a grave error has occurred?
Maybe the patch from the mailing list can be added to the repo? apparently it still requires the patched file to be built with -O0... there had to be an exception somehow so that -O0 is only used for this single file.
Shouldn't this also have popped up in the Travis build for Boost-1.66.0-intel-2018a-Python-3.6.4.eb? I wonder why it didn't..

**Comment by boegel** [comment]
@mstud This problem only occurs when you are building Python 3.6.4 in an environment with a strict stack limit, see the discussion in https://github.com/easybuilders/easybuild-easyconfigs/issues/6484 .

We have added a workaround for this problem recently in the Python easyblock, together with a check for `import hashlib` to catch the problem, which will be included in EasyBuild 3.6.2, see https://github.com/easybuilders/easybuild-easyblocks/pull/1441 .

Please try re-installing Python 3.6.4 with the updated easyblock from https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/p/python.py (download via 'Raw', and provide it to `eb` via `--include-easyblocks python.py`).

The Travis build only runs unit tests, it doesn't perform the actual builds. This could have been caught in test reports that are submitted, but most people apparently run in an environment with `ulimit -s unlimited` set, so this problem didn't pop up (and it took us a while to figure out what the cause of the problem was or how to work around it).

**Comment by mstud** [comment]
Thanks, that indeed solved the problem.
