### ISSUE TITLE
Qt compilation error due to openssl 1.1.0 on debian 9

### ISSUE THREAD

**Issue by vwkoppejan** [easybuilders/easybuild-easyconfigs#6644]
Similar to #5614, building Qt-4.8.7 on debian 9.5 fails due the openssl api changes that were put in openssl-1.1.0.

as a quick fix I've added OpenSSL.1.0.2g as build dependency and it now compiles ok. I think this is more a Qt4 than an easybuild problem but nonetheless it's enjoying.

**Comment by boegel** [comment]
@vwkoppejan We prefer relying on the system installed OpenSSL for security reasons, since includes `OpenSSL` as an EasyBuild dependency implies fixing the version.

We may revisit this soon though, with an `OpenSSL` wrapper that can be easily updated when a bugfix release becomes available, similarly to how we plan to deal with Java (see #5203).

**Comment by Micket** [comment]
Qt4 is quite dead now, and also fixes were merged. Closing this.
