### ISSUE TITLE
Using Python 3.7.0 for 2018b toolchains might be a problem

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyconfigs#6682]
There are some packages that are still not Python 3.7 compatible which may be a reason to downgrade the 2018b toolchains Python to the latest 3.6.x.

Problem codes detected so far:
- TensorFlow
- protobuf-python

**Comment by boegel** [comment]
I think @mboisson also had some other problematic Python packages with Python 3.7, which doesn't seem to be fully backwards compatible with earlier Python 3.x versions, see also the problems I ran into with `pandas`: https://github.com/pandas-dev/pandas/issues/21785

Should we revisit the Python 3.x versions we picked for `2018b` and go forward with 3.6.6 rather than 3.7.0 now we still can?

cc @easybuilders/easybuild-easyconfigs-maintainers

**Comment by mboisson** [comment]
Yes. I have recompiled our wheels for Python 3.7 around mid-July. Here are the ones that did not recompile correctly for one reason or another : 

- cutadapt
- fuel
- HTSeq
- mdtraj
- msgpack_python
- msmbuilder
- openslide_python
- pysam
- python_Levenshtein
- python_lzo
- PyWavelets
- ray
- velocyto

**Comment by akesandgren** [comment]
If 3.6.6 is decided on, instead of 3.7.0, I can change my PR's to start with (and I +1 on dropping all 3.7's)

**Comment by boegel** [comment]
#6703 is merged, switch to Python 3.6.6 for `2018b` toolchain generation is done in https://github.com/easybuilders/easybuild-easyconfigs/pull/6710

**Comment by boegel** [comment]
Both #6703 and #6710 have been merged, so closing this too...
