### ISSUE TITLE
Install netCDF-Fortran with F90 module

### ISSUE THREAD

**Issue by ahmedhany93** [easybuilders/easybuild-easyconfigs#6816]
After installing  `netCDF-Fortran/4.4.4-intel-2017a` ,  I ran the command:
`$ nf-config --has-f90`
the result was:
`$ no`
After investigations, I found that netCDF has to be built with options
```FC=gfortran F90=gfortran --enable-shared --enable-static```

**Comment by ocaisa** [comment]
Please take a look at this ticket with netCDF to explain this confusing result https://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg13399.html

Short answer: it has F2003 support which includes F90

Ok to close?

**Comment by boegel** [comment]
@ahmedhany93 `FC=gfortran F90=gfortran` is already done automatically by EasyBuild, and I doubt using `--enable-shared --enable-static` is going to make it build with (only) F90 support?

Also, with the above in mind, this would actually limit the capabilities of the `netCDF` installation rather than enhance them?

**Comment by ahmedhany93** [comment]
Thanks for your help. I have edited my code to use f03.
