### ISSUE TITLE
icc & ifort sanity checks fail with intel 2018 update 4 

### ISSUE THREAD

**Issue by DanielTosello** [easybuilders/easybuild-easyconfigs#7070]
for some reason i haven't pinned down yet, the following block fails with intel 2018 u4 compiler, and i assume with some others: 
```
        binprefix = 'bin/intel64'
        libprefix = 'lib/intel64'
        if LooseVersion(self.version) >= LooseVersion('2011'):
            if LooseVersion(self.version) <= LooseVersion('2011.3.174'):
                binprefix = 'bin'
            elif LooseVersion(self.version) >= LooseVersion('2013_sp1'):
                binprefix = 'bin'
            else:
                libprefix = 'compiler/lib/intel64'
```

Build fails as icc & ifort are installed into bin/ but sanity check assumes 'bin/intel64'. I'm guessing that LooseVersion doesn't think 2018_sp4 >= 2013_sp1.

Have worked around it locally (see below) but thought it'd help to report it.

Adding something like:
```
postinstallcmds = ['mkdir bin/intel64 && ln -s $EBROOTIFORT/bin/ifort bin/intel64']
```
to the .eb resolves the issue, as does simply setting `binprefix = 'bin'` in the block.

**Comment by boegel** [comment]
Thank you very much for the report @DanielTosello!

`bin/icc` is there for all `2018.*` installations up until `2018.3.*`, but it got moved apparently for `2018.4`. 

A similar issue has popped up for Intel MPI, see #1546 . It seems like Intel is moving things around again, I'm sure they have very good reasons for doing so... :-/

We'll get this sorted in the relevant easyblock, by adding another version check...

cc @damianam

**Comment by DanielTosello** [comment]
Slight clarification: It's still in that location (`bin/icc`), the sanity check is looking in the wrong location (`bin/intel64/icc`).

Normally i'd put a bit more work into determining the actual cause but i'm a bit pressed for time right now... sorry about that.

**Comment by boegel** [comment]
@DanielTosello Can you share the easyconfig file you were using here?

The version checks assume that you'll be using a `version` like `2018.4.*`, is that what you're using?

**Comment by DanielTosello** [comment]
We're using "2018.u4", which is in line with previous toolchains... but i
can understand why that might cause a problem. It's actually kind of weird
that it hasn't before if that is the cause.

It's a new toolchain, so now's a good time to change that convention if we
need to.

**Comment by boegel** [comment]
@DanielTosello Indeed better stick to the versioning scheme we're using in the central repository, or you're doomed to run into surprises... :)

**Comment by boegel** [comment]
I'm reopening this since I'm seeing the sanity check fail for icc `2018.4.274` because the `icc` binary is not found via `which icc`, which indicates that the `$PATH` updates included in the generated module file are no longer correct for this version.

Did you ever got the installation of icc 2018 update 4 to work without modifications to the `icc` easyblock @DanielTosello?

**Comment by boegel** [comment]
The problem in my case basically also turned out to be a versioning issue... The internal version for the 2018 update 4 release of the Intel compilers turns out to be `2018.5.274` (rather than `2018.4.*` as you may expect).

The `icc` easyblock requires that you use the internal version, since it uses the `compilers_and_libraries_<INTERNAL_VERSION>/linux` subdirectory when determining which paths to update in the generated module file.

I'll look into a good way of catching this problem more clearly. Probably explicitly checking for that directory in the sanity check would help.

**Comment by boegel** [comment]
Additional check in sanity check added in https://github.com/easybuilders/easybuild-easyblocks/pull/1577

**Comment by DanielTosello** [comment]
I see this all happened while i was asleep. Good old intel and their
consistent paths.
