### ISSUE TITLE
Qt5-5.10.1 missing build deps Bison and gperf

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#7179]
We build from a CentOS7 machine with pretty minimal system installation, and I encountered a problem that the WebEngine component needs Bison and gperf, these should be added as build deps.

https://github.com/easybuilders/easybuild-easyconfigs/blob/67f0180ee26110d4a449049476e8bdd58072ebc2/easybuild/easyconfigs/q/Qt5/Qt5-5.10.1-foss-2018b.eb#L18

**Comment by JackPerdue** [comment]
WebEngine also needs a Python.

WARNING: Python version 2 (2.7.5 or later) is required to build QtWebEngine.

RHEL7 provides python-2.7.5 so the Qt5 build blindly used the system python instead of the Python will be used with DOLFIN.  However, RHEL6 is 2.6.6 so the problem jumps out immediately.  So I've added these dependencies.

    ('gperf', '3.1'),
    ('Python', '3.6.4'),

Maybe Python is only a builddep and no actual python files are installed (and compiled).  But with gperf and Python on RHEL6, Qt5 is broken if WebEngine is wanted (and it must be since it is requested in the EasyConfig).

**Comment by JackPerdue** [comment]
Upon further investigation, it needs a builddep of Python-2.7.14 (for 2018a) and not a dep of 3.6.4.  Regardless, it won't build on RHEL6 unless you comment out "#check_qtwebengine = True" due to glibc not being new enough.

**Comment by drwhitehouse** [comment]
Just noting that I concur with @JackPerdue - have been having issues building this as a dependency of OpenFOAM. Commenting out "check_qtwebengine = True" appears to resulted in a bit of progress.

**Comment by boegel** [comment]
fixed in #7300, you should not be seeing this problem anymore when using the Qt5 5.10.1 (or more recent) easyconfigs included in EasyBuild 3.8.0
