### ISSUE TITLE
Failed to install Clang 7.0.0

### ISSUE THREAD

**Issue by XHotSniperX** [easybuilders/easybuild-easyconfigs#7561]
We want to install Clang on our cluster with Easybuild (Clang 3.8 is already installed but we need the newer one) but it fails. There are 2 log files.
[clang-log.zip](https://github.com/easybuilders/easybuild-easyconfigs/files/2838179/clang-log.zip)

I could not find the issue why it fails. Do you have an idea?

**Comment by boegel** [comment]
@XHotSniperX A handful of tests failed, reason is unclear to me.

We recently added the possibility to skip running the Clang tests, because we frequently run into a handful of failing tests for no apparent reason.

Can you try adding `skip_all_tests = True` to the Clang easyconfig file you are using?
Note that this requires EasyBuild v3.8.0 or newer (cfr. the changes to the Clang easyblock in https://github.com/easybuilders/easybuild-easyblocks/pull/1584).

**Comment by XHotSniperX** [comment]
@boegel Many thanks for the answer! We will try it. By the way, is it easy to edit the easybuild configuration so that it installs the 7.0.1 version? Could also give that a try.

**Comment by ocaisa** [comment]
@XHotSniperX Can we close this since the install is working for you?

**Comment by XHotSniperX** [comment]
Sure, close it. Thanks.
