### ISSUE TITLE
BFD linker in binutils 2.31.1 crashes when doing relocatable linking in PLUMED

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#7822]
While building PLUMED for intel/2019a, we encountered a assertion error in ld (BFD).

```
ld -r -o install/kernel.o ../adjmat/ActionWithInputMatrix.o ../adjmat/AdjacencyMatrixBase.o ...
```
resulted in
```
ld: BFD (GNU Binutils) 2.31.1 assertion fail elf.c:3583
```

ld.gold (from the same binutils) works fine. Using 2.28.0, both linkers work.

**Comment by boegel** [comment]
@akesandgren Does this ring any bells for you?

**Comment by akesandgren** [comment]
No, haven't gotten that far with 2019a yet.

**Comment by Micket** [comment]
Problem persist even when using binutils 2.32.

**Comment by boegel** [comment]
@Micket We could backport the fix to older `PLUMED` easyconfigs?

**Comment by casparvl** [comment]
Just FIY: I ran into this problem with PLUMED-2.4.2-intel-2018b.eb. Since that is the PLUMED version used in EasyBuild v 3.8.1 as a dependency in foss-2018b, I also picked that version of PLUMED for trying build a CP2K with PLUMED. Would be nice if the change was backported :)

**Comment by Micket** [comment]
@casparvl 
But the intel-2018b version has the fix?
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.2-intel-2018b.eb#L34

I would agree that it should probably be present in foss-2018b as well.

**Comment by casparvl** [comment]
@Micket 

Silly: we had a local copy, of PLUMED-2.4.2-intel-2018b.eb in our own repository. Probably, one of my colleagues created this before the fix was available and never got it to work...

Anyway, I've deleted our local copy and will try a rebuild, I assume this solves it.
Regarding the foss-2018b version, this easyconfig https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.2-foss-2018b.eb (without fix, from the official repo), installed correctly for me. So, the problem seems to be intel toolchain specific (?)

**Comment by Micket** [comment]
Alright. It sounds like we can just close this.
