### ISSUE TITLE
Split out rgdal from R and make it it's own RPackage/Bundle

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-easyconfigs#8328]
GDAL stuff is pretty specialized, it brings in several additional dependencies for the already big R package.

There is also some concern raised recently; I asked the developer of libgeotiff (and some of the other GDAL libraries i think) about the latest stable release, and when I asked if libgeotiff 1.5.1 was a stable release, Even responds:

> yes. I've updated github releases to make that clear
> See release announcements:
> https://lists.osgeo.org/pipermail/geotiff/2019-March/000861.html
> https://lists.osgeo.org/pipermail/geotiff/2019-March/000862.html
> and particular the PROJ >= 6 required dependency (which might break other
> packages not ready for it)

So, for these reasons, it would be easier to deal with if it was isolated *going forward*

**Comment by fizwit** [comment]
In general, any R extension that requires an external library should be a separate bundle.

In order to remove Rgdal the following list of extensions have to be removed. rgdal <- sf <- spdep <- adegent <- adephyl. spdep has been part of the R easybuild for many years. I will submit R-3.6.0-foss-2019a sans rgdal and upstream dependencies.

**Comment by boegel** [comment]
rgdal has been separate since foss/2019a (R 3.6.0 in EasyBuild v4.0.0), see #8826, so closing this...
