### ISSUE TITLE
Python/3.7.2-GCCcore-6.4.0 issue with -fPIC during linking

### ISSUE THREAD

**Issue by moravveji** [easybuilders/easybuild-easyconfigs#8644]
Dear colleagues,

I would like to install Python/3.7.2-GCCcore-6.4.0, but I get the following error message: 

```bash
<dir-apps>/software/binutils/2.28-GCCcore-6.4.0/bin/ld.gold: error: <dir-apps>/software/libreadline/8.0/lib/libreadline.a(readline.o): requires dynamic R_X86_64_PC32 reloc against 'rl_readline_state' which may overflow at runtime; recompile with -fPIC
```

I am attaching the debug logs and the EB easyconfig file. I'd be grateful to hear your insights.

Best,
Ehsan
[Python-3.7.2.zip](https://github.com/easybuilders/easybuild-easyconfigs/files/3446238/Python-3.7.2.zip)

**Comment by moravveji** [comment]
I am gonna repeat now, with more recent `binutils` and `libreadline` modules, and see whether that helps! Will post updates, soon.

**Comment by moravveji** [comment]
Any updates here?

**Comment by boegel** [comment]
@moravveji It seems like you have something custom in your configuration that is causing this problem, since others are not seeing it (as far as I know).

Do you mind sharing the output of "`eb --show-config`"?

Also, it seems like the `libreadline` built with the `dummy` toolchain is being picked up as a dependency for `Python-3.7.2-GCCcore-6.4.0.eb`.

That may be the cause of the problem, since it seems like that one gets built without `-fPIC`.

**Comment by moravveji** [comment]
@boegel: Thanks for the tips.
In fact, I tried again using `libreadline/8.0-GCCcore-6.4.0`, and got the same error. I assume somewhere in my dependency tree, there is a dummy libreadline pollution, which I gotta spot and fix. I have email you the output of `--show-config`. 
I will update this ticket soon.

**Comment by moravveji** [comment]
Alright ... the SQLite had a dependency on the dummy readlibline, which I fixed. Now, the Python build flows smoothly. Thanks for the tip, and I shall close this ticket.

**Comment by boegel** [comment]
Glad to hear you got it sorted out, thanks for the update!
