### ISSUE TITLE
Perl-5.28.0-GCCcore-7.3.0.eb failed 

### ISSUE THREAD

**Issue by alchemroz** [easybuilders/easybuild-easyconfigs#8874]
Hello, 
         I tried to install Perl-5.28.0-GCCcore-7.3.0.eb, in a Centos 7. Unluckly I got an error (in attachment)
[easybuild-Perl-5.28.0-20190905.151254.Lmobu.log](https://github.com/easybuilders/easybuild-easyconfigs/files/3579719/easybuild-Perl-5.28.0-20190905.151254.Lmobu.log)

I tried to solve looking for a similar issue (#7007) using 

eb --from-pr 7007 ....

but it did not work, probably the problem is different. 

Thanks for help,
S.

**Comment by boegel** [comment]
@alchemroz You're basically running into this problem: https://serverfault.com/questions/145288/make-error-when-compiling-perl-5-12-1-rhel-5-5 (see also #8859).

One or more environment variables probably include an empty entry, check `$CPATH` and `$C_INCLUDE_PATH`.

The easiest thing to do is to just unset those environment variables before running `eb`.

It seems like we should be doing that automatically, since `Perl` is quite sensitive to it...

**Comment by alchemroz** [comment]
Dear @boegel, 
                        I had the CPATH variable initialized for a test with Intel Optane, I put an empty entry and now it works properly.

Many Thanks,
S.

**Comment by boegel** [comment]
fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/1800, thanks again for reporting this @alchemroz!
