### ISSUE TITLE
PyTorch test failure

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#8878]
```
======================================================================
FAIL: test_affine_3d_rotateRandom (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/PyTorch/1.0.1/foss-2018b-Python-3.6.6/pytorch-1.0.1/test/common_utils.py", line 117, in wrapper
    fn(*args, **kwargs)
  File "test_nn.py", line 6036, in test_affine_3d_rotateRandom
    assert np.allclose(affine_tensor[0, i, r, c], grid_out[:3], atol=1e-5)
AssertionError

----------------------------------------------------------------------
Ran 1247 tests in 321.923s

FAILED (failures=1, skipped=626, expected failures=2)
Traceback (most recent call last):
  File "test/run_test.py", line 431, in <module>
    main()
  File "test/run_test.py", line 423, in main
    raise RuntimeError(message)
RuntimeError: test_nn failed!
 (at easybuild/tools/run.py:501 in parse_cmd_output)
== 2019-09-05 16:37:00,011 easyblock.py:3050 WARNING build failed (first 300 chars): cmd "  export PYTHONPATH=/dev/shm/PyTorch/1.0.1/foss-2018b-Python-3.6.6/pytorch-1.0.1/build/lib.linux-x86_64-3.6:$PYTHONPATH && python test/run_test.py --exclude autograd cpp_extensions c10d torch --verbose " exited with exit code 1 and output:
which: no nvcc in (/apps/eb/software/Ninja/1.8.2-foss-2
== 2019-09-05 16:37:00,011 easyblock.py:294 INFO Closing log for application name PyTorch version 1.0.1
```

**Comment by boegel** [comment]
@branfosj Does this ring a bell for you?

**Comment by branfosj** [comment]
This isn't a test I've had an issue with. It is also one of those tests that has many asserts (46000) of the line that fails. So narrowing down when it fails nay help debug the issue. There is a possibility that the problem is in the reference generated by numpy.

@verdurin - narrow down by downloading:
- https://raw.githubusercontent.com/pytorch/pytorch/v1.0.1/test/common_cuda.py
- https://raw.githubusercontent.com/pytorch/pytorch/v1.0.1/test/common_nn.py
- https://raw.githubusercontent.com/pytorch/pytorch/v1.0.1/test/common_utils.py
- https://raw.githubusercontent.com/pytorch/pytorch/v1.0.1/test/expecttest.py

And then run the file I've attached here, which is the `test_affine_3d_rotateRandom` extracted with the needed helper functions. It follows the old fashioned part of just printing everything it is comparing.

[test_affine_3d_rotateRandom.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/3594720/test_affine_3d_rotateRandom.txt)

**Comment by Micket** [comment]
We have given up fixing all failed tests in pytorch and just accept a few of them by default now.
