### ISSUE TITLE
Bazel 0.27+ requires Python3

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-easyconfigs#9222]
It seems Bazel now needs Python3:

```
Error occurred while attempting to use the default Python toolchain (@rules_python//python:
autodetecting_toolchain).
According to '/usr/bin/python -V', version is 'Python 2.7.5', but we need version 3. PATH is:

/sw/installed/Java/11.0.2:/sw/installed/Java/11.0.2/bin:/sw/installed/binutils/2.31.1-GCCcore-8.2.0/bin:/sw/installed/GCCcore/8.2.0/bin:/sw/installed/EasyBuild/4.0.1/bin:/usr/lib64/qt-3.3/bin:/sw/taurus/tools
/slurmtools/default/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/home/s3248973/.local/bin

Please ensure an interpreter with version 3 is available on this platform as 'python3' or 'python', or else register an appropriate Python toolchain as per the documentation for py_runtime_pair (https://githu
b.com/bazelbuild/rules_python/blob/master/docs/python.md#py_runtime_pair).

Note that prior to Bazel 0.27, there was no check to ensure that the interpreter's version matched the version declared by the target (#4815). If your build worked prior to Bazel 0.27, and you're sure your ta
rgets do not require Python 3, you can opt out of this version check by using the non-strict autodetecting toolchain instead of the standard autodetecting toolchain. This can be done by passing the flag `--ex
tra_toolchains=@rules_python//python:autodetecting_toolchain_nonstrict` on the command line or adding it to your bazelrc.
----------------
Note: The failure of target //src:create_embedded_tools (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------

```

**Comment by boegel** [comment]
@Flamefire Thanks for the bug report!

In which context were you hitting this? Was `Bazel` being installed as a (build) dependency for `TensorFlow`?

@akesandgren Why did we miss this, do you have `python3` installed in the OS as well? We've only installed this recently, so I'm a bit surprised we haven't seen this sooner...

**Comment by Flamefire** [comment]
> Was Bazel being installed as a (build) dependency for TensorFlow?

Correct. I'm trying TensorFlow with CUDA but failed so far... Symlinks in the toolchains are not handled by bazel

**Comment by boegel** [comment]
@Flamefire Can you clarify what you mean exactly? We may have fixed an issue like this recently...

Which `TensorFlow` easyconfig file are you trying to install?
Which `EasyBuild` version are you using?

**Comment by akesandgren** [comment]
@boegel Haven't tried TF 2 yet so I wouldn't know.

**Comment by Flamefire** [comment]
I reported it upstream to TF (I guess it should rather go to bazel): https://github.com/tensorflow/tensorflow/issues/33975

Basically: Bazel creates some CUDA toolchain definition file containing resolved paths but the include-dependency checker uses non-resolved paths (symlinks) and reports a missing defined dependency although they are the same paths.

Using TF2 EasyConfig modified to use fosscuda with EB 4.0.1

**Comment by boegel** [comment]
I recall running into similar issues, and I some workaround for it...
But then I ended up not needing it anymore, I think.
I'll try to figure out what I ended up doing exactly...

We have a local installation of TensorFlow 2.0.0 with an updated `fosscuda`, because the CUDA included in `fosscuda/2019a` is not recent enough (see https://github.com/easybuilders/easybuild-easyconfigs/pull/9028#issuecomment-537927528).

**Comment by boegel** [comment]
OK, this patch should fix the problem: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.14.0_fix-cuda-build.patch .

Are you includes this patch, as well as `TensorFlow-1.14.0_fix-cuda-mpi.patch` in the easyconfig file you're using?

Also make sure you use a sufficiently recent `CUDA` version...

I'm hoping to open a PR for `TensorFlow` 2.0.0 with `fosscuda/2019b` soon (I was blocked by a lack of an updated `SciPy-bundle` for the `2019b` toolchain, but that's being fixed in #9016)

**Comment by boegel** [comment]
Ah, now I see why we didn't see the issue of Bazel 0.27+ requiring Python 3...
We're using an older Bazel version for building TensorFlow (0.26.1).

**Comment by Flamefire** [comment]
Correct. The current TF did raise the max requirement to 0.29.1 so I wanted to give it a try and run into this.

**Comment by Flamefire** [comment]
> I was blocked by a lack of an updated SciPy-bundle for the 2019b toolchain, but that's being fixed in #9016

I tried to build on top of that but got `Missing dependencies: SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4`. The PR adds it for foss/2019b. Does it really need one for fosscuda not just foss? I though subsets are ok

**Comment by Flamefire** [comment]
Similar for cuDNN: With neither `('cuDNN', '7.6.4.38', '-CUDA-10.1.243'),` nor `('cuDNN', '7.6.4.38'),` as a dependency it is able to find `cuDNN-7.6.4.38-CUDA-10.1.243.eb` :/

**Comment by boegel** [comment]
@Flamefire `fosscuda` is not a superset of `foss`.

The difference is that in `fosscuda`, the `OpenMPI` is built `CUDA`-aware (while it's not in `foss`, since there is no `CUDA`).

That implies that you'll need a `SciPy-bundle` that is installed with `fosscuda` rather than `foss`. Taking the easyconfig from #9016 and changing the toolchain should be sufficient...

For `cuDNN`, make sure the easyconfig can be found in the robot search path, by passing the location to `--robot` (see also https://easybuild.readthedocs.io/en/latest/Using_the_EasyBuild_command_line.html#controlling-robot-search-path).

Also, for easyconfig that were installed with a `system` toolchain (no toolchain mentioned in the easyconfig filename), you need to specify that the toolchain should not be inherited from the parent:

```python
dependencies = [
    ('cuDNN', '7.6.4.38', '-CUDA-10.1.243', True),
]
```

see also https://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html#specifying-dependencies-using-system-toolchain

**Comment by Flamefire** [comment]
Great! There does not seem to be a clear path on how to install such binary packages. This applies to cuDNN and NCCL. Both have versions for CUDA 10.1 (no patch level) but common practice seems to be to depend on full toolchains. What would the best option be? I'd say 'cuDNN-7.6.4.38-CUDA-10.1`, but should loading this load a CUDA package? Which one? The problem is: It is a waste to have 2 packages for fosscuda/2019a and 2019b. You only need 1.

**Comment by boegel** [comment]
Easyconfig that use the `system` toolchain can be combined with easyconfigs using any other toolchain.
But we do stick to a single version of a dependency per toolchain generation (`2019a`, `2019b`, etc.), to avoid conflicts between different easyconfigs using the same toolchain generation.

So, for `cuDNN`, we already have easyconfigs using a `2019a` toolchain that depend on `cuDNN` `7.6.4.38` (which uses `gcccuda/2019a` as toolchain mostly because of where it's placed in a module hierarchy).
For easyconfigs using a `2019b` toolchain, we'd use the latest `cuDNN` (and then that version is fixed for the `2019b` generation).

W.r.t. toolchain to use for `cuDNN`, strictly speaking `system` is sufficient, but we've used a non`-system` toolchain mostly because of placement in a module hierarchy (@akesandgren can probably help clarify this, see also #9178 for `CUDA` in `fosscuda/2019b` for example).

**Comment by Flamefire** [comment]
> So, for cuDNN, we already have easyconfigs using a 2019a toolchain that depend on cuDNN 7.6.4.38 (which uses gcccuda/2019a as toolchain mostly because of where it's placed in a module hierarchy).

So this means for every combination of CUDA 10.1.x with a compiler (GCC, Clang, Intel) you need a separate cuDNN package although it is exactly the same? Isn't that a complete waste?

I mean " stick to a single version of a dependency per toolchain generation" can be enforced in the other direction: All 2019a using packages use cuDNN-7.6.4.38-CUDA-10.1, all 2019b use the same, all icccuda/whatever use cuDNN-7.42.42.42-CUDA-10.1 etc. Why reverse the dependency and make a compiler independent cuDNN depend on the compiler?

Can't one at least use `('CUDA', '10.1.243')` as the Toolchain for cuDNN/NCCL? This removes one dimension of the matrix. Again: Even better would be none at all and only use CUDA-10.1 as suffix.

> For easyconfigs using a 2019b toolchain, we'd use the latest cuDNN (and then that version is fixed for the 2019b generation).

The latest is the same as for fosscuda/2019a. So you'd have duplicated packages which I'd avoid

**Comment by akesandgren** [comment]
Not quite sure if this is what @boegel wanted me to explain but...

CUDA must be at GCCcore level (or Compiler level in HMNS) when using HMNS since it needs to expand the MODULEPATH to Compiler/GCC-CUDA (or Compiler/intel-CUDA) when it is loaded.

A CUDA at SYSTEM (or Core in HMNS) can't expand MODULEPATH to GCC-CUDA since it wouldn't know where it is, in GCC or intel land...

For cuDNN, NCCL and such they depend on CUDA and thus need to be at the same level.

Hope that makes it a bit clearer.

**Comment by Flamefire** [comment]
Uff... I'm no expert there, but did I understand it correctly, that the correct toolchain for cuDNN/NCCL should be gcccuda/xxx? That would be slightly better than fosscuda

**Comment by akesandgren** [comment]
Yes, gcccuda is what we currently use for those. All this CUDA stuff is a moving target still WIP, but partially pending a change in framework due to the merge of icc+ifort into using  combined iccifort as lowest level. That affects iccifortcuda, and I wan't that done before we start moving forward with fosscuda/intelcuda at 2019b. Then we can start looking at the cuda related packages in more detail.

**Comment by Flamefire** [comment]
@boegel I opened PRs which allow to build Tensorflow 2 with fosscuda/2019b just now. Tested on our cluster.
