### ISSUE TITLE
matplotlib problem with missing __init__

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyconfigs#9314]
matplotlib-2.2.4-foss-2019a-Python-2.7.15.eb currently lacks an ```__init__``` in mpl_toolkits.
Either manually add it, or don't use pip for matplotlib.

Could be related to https://github.com/pypa/pip/issues/7265

**Comment by boegel** [comment]
We should probably also consider adding `python -c 'from mpl_toolkits.mplot3d import Axes3D'` to the sanity check for `matplotlib`, to catch this issue...

**Comment by boegel** [comment]
More info (though nothing very useful it seems) via https://github.com/matplotlib/matplotlib/issues/8189/ .

I'm a bit baffled that not more people are running into this, since (the matplotlib docs)[https://matplotlib.org/3.1.1/users/installing.html] mention to use `pip install`

There seems to be some magic in Homebrew's `matplotlib-basemap` that could solve this, see https://github.com/Homebrew/homebrew-python/issues/112

**Comment by boegel** [comment]
https://github.com/pypa/pip/issues/1924 and https://github.com/pypa/setuptools/issues/1097 have a better discussion on why `pip` trashes the `__init__.py` for namespace packages.

It seems to boil down to this:

* the `__init__.py` isn't actually needed to make the `import` work, as long as the package is installed in a standard location (see https://github.com/pypa/setuptools/issues/1097#issuecomment-439660425)

* the `__init__.py` is always trashed, but it's only a problem when the package is being installed in a non-standard location by using `--prefix` (no problems if `sudo pip install` or `pip install --user` is used)

**Comment by boegel** [comment]
Some more digging: this is only a problem for `matplotlib` installed with `pip install --prefix` using Python 2. It's *not* a problem when using Python 3.3+ (because of the "native namespace packages" concept, see https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages).

**Comment by boegel** [comment]
fixed in #9415, #9416, #9417 & enhanced sanity check for `matplotlib` 3.x with Python 3 in #9413 & #9414...
