### ISSUE TITLE
h5py 2.9.0 broken on ppc64le

### ISSUE THREAD

**Issue by branfosj** [easybuilders/easybuild-easyconfigs#9395]
h5py 2.9.0 is broken on ppc64le - https://github.com/h5py/h5py/issues/1222

Locally we've moved 2019a and 2019b to use 2.10.0 instead, which contains the fix that is mentioned in the h5py bug report.

Would you like me to submit a pull request for bumping h5py to 2.10.0 in 2019b?

**Comment by boegel** [comment]
@branfosj The `h5py` easyconfigs for the `2019b` toolchain have only been added recently, so there's still a possibility to replace them with `h5py` 2.10.0.

But it would have to be done really soon, since we're planning to close up things for the upcoming EasyBuild v4.1.0 release tomorrow evening (Fri Nov 29th).

Note that we'll also need to bump `h5py` in the TensorFlow easyconfigs using a `2019b` toolchain (nothing else currently merged is using them yet).
That's best done in separate PRs per `TensorFlow` easyconfig (to speed up test reports).
