### ISSUE TITLE
Python/2.7.16-GCCcore-8.3.0 needs wcwidth for sanity_pip_check

### ISSUE THREAD

**Issue by JackPerdue** [easybuilders/easybuild-easyconfigs#9582]
Re: https://github.com/easybuilders/easybuild-easyconfigs/pull/9516

Testing some PRs here (e.g. Faber-0.3-GCCcore-8.3.0.eb) I get failures from "pip check" with 2.7.16.  To test:

1) build/load the Python 2.7.16 module
2) run: pip check

Here it complains about a missing wcwidth. 

I see wcwidth was added to:
-- Python-3.7.2-GCCcore-8.2.0.eb
-- Python-3.7.4-GCCcore-8.3.0.eb
but not any Python 2.7 files.

**Comment by boegel** [comment]
@JackPerdue We overlooked this in EasyBuild v4.1.0, but this issue is already fixed in #9479 (to be included with EasyBuild v4.1.1).

You should be able to fix your Python 2.7.* installations with `eb --from-pr 9479 --rebuild --skip`, which will just add the missing extensions to your existing `Python/2.7.*` installations

**Comment by JackPerdue** [comment]
That worked after restoring write permissions and unsetting EASYBUILD_READ_ONLY_INSTALLDIR

How will people that have already built the older version know to run that step when the new one comes out?

**Comment by boegel** [comment]
@JackPerdue We try to clearly mention that in the release notes, can we do more?
